version: "3.9"

services:
  db:
    container_name: db-praktikum7
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_volumes:/var/lib/mysql

volumes:
  db_volumes:
    name: "db_volumes"
